# Generated by Django 5.1.6 on 2025-02-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, unique=True),
        ),
    ]
