# Generated by Django 5.1.6 on 2025-02-27 15:02

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_alter_conversation_id_alter_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 27, 15, 2, 15, 293284, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
